//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.22 at 07:44:07 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/hello", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.hello;
